name: Preprocess Dataset from ZIP
on:
  push:
    paths:
      - 'preprocessing/automate_NurAriefFauzianR.py'
      - 'lungdataset_raw/**'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn imbalanced-learn

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_NurAriefFauzianR.py lungdataset_raw/dataset_lung.zip dataset_med.csv preprocessing/dataset_preprocessing.csv

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v3
        with:
          name: preprocessed-data
          path: preprocessing/dataset_preprocessing.csv
