name: Preprocess Dataset from ZIP
on:
  push:
    paths:
      - 'preprocessing/automate_NurAriefFauzianR.py'
      - 'lungdataset_raw/**'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn imbalanced-learn

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_NurAriefFauzianR.py lungdataset_raw/dataset_lungs.zip dataset_med.csv preprocessing/dataset_preprocessing.csv

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-data
          path: preprocessing/dataset_preprocessing.csv
      - name: Zip preprocessed dataset
        run: |
          cd preprocessing
          zip dataset_preprocessing.zip dataset_preprocessing.csv

      - name: Commit ZIP file ke repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add preprocessing/dataset_preprocessing.zip
          git commit -m "Auto: ZIP hasil preprocessing"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
